use borsh::{BorshDeserialize, BorshSerialize};

#[derive(Debug, Clone)]
/// An onchain event containing standardized stroemnet events.
pub enum ChainEvent {
    Commitment(CommitmentV1),
    Reveal(RevealV1),
    Refund(RefundV1),
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    BorshSerialize,
    BorshDeserialize,
    serde::Serialize,
    serde::Deserialize,
)]
/// Standardized commitment event for v1 stroemnet swaps.
pub struct CommitmentV1 {
    /// A unique identifier for the swap, generated by the client when initiating the swap
    pub swap_id: [u8; 32],
    /// Addresses involved in this swap
    pub addresses: AddressesV1,
    /// Amount being swapped encoded with decimals
    pub amount: AmountV1,
    /// The hash of the secret that allows for redemption of funds.
    pub secret_hash: [u8; 32],
    /// A timestamp in seconds since the UNIX epoch indicating when the swap can be unlocked by the recipient.
    /// (Used for refunds)
    pub unlock_ts: u64,
    /// The channel from which the user is sending, i.e. the stroemnet channel id.
    pub source: u8,
    /// The channel to which the user is sending, i.e. the stroemnet channel id.
    pub destination: u8,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    BorshSerialize,
    BorshDeserialize,
    serde::Serialize,
    serde::Deserialize,
)]
/// Standardized addresses involved in a v1 stroemnet swap.
pub struct AddressesV1 {
    /// The address of the sender.
    pub sender: String,
    /// The address of the receiver.
    pub receiver: String,
    /// The address of the sender on the destination channel
    pub sender_destination: String,
}

impl AddressesV1 {
    pub fn new(sender: String, receiver: String, sender_destination: String) -> Self {
        Self {
            sender,
            receiver,
            sender_destination,
        }
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    BorshSerialize,
    BorshDeserialize,
    serde::Serialize,
    serde::Deserialize,
)]
/// Standardized amount for v1 stroemnet swaps, containing the value as a string and the number of decimals.
pub struct AmountV1 {
    /// The amount value as a string, encoded with the appropriate number of decimals for the channel.
    pub value: String,
    /// The number of decimals used by the channel's native token, used to decode the value string into a human-readable format.
    pub decimals: u8,
}

impl AmountV1 {
    pub fn new(value: String, decimals: u8) -> Self {
        Self { value, decimals }
    }

    pub fn at_least(&self, required: &AmountV1) -> bool {
        if self.decimals != required.decimals {
            return false;
        }
        match (self.value.parse::<u128>(), required.value.parse::<u128>()) {
            (Ok(have), Ok(need)) => have >= need,
            _ => false,
        }
    }
}

impl CommitmentV1 {
    pub fn new(
        swap_id: [u8; 32],
        addresses: AddressesV1,
        amount: AmountV1,
        secret_hash: [u8; 32],
        unlock_ts: u64,
        source: u8,
        destination: u8,
    ) -> Self {
        Self {
            swap_id,
            addresses,
            amount,
            secret_hash,
            unlock_ts,
            source,
            destination,
        }
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    BorshSerialize,
    BorshDeserialize,
    serde::Serialize,
    serde::Deserialize,
)]
/// Standardized reveal event for v1 stroemnet swaps.
pub struct RevealV1 {
    /// The unique identifier for the swap.
    pub swap_id: [u8; 32],
    /// The secret used to redeem the funds.
    pub secret: [u8; 32],
}

impl RevealV1 {
    pub fn new(swap_id: [u8; 32], secret: [u8; 32]) -> Self {
        Self { swap_id, secret }
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    BorshSerialize,
    BorshDeserialize,
    serde::Serialize,
    serde::Deserialize,
)]
/// Standardized refund event for v1 stroemnet swaps.
pub struct RefundV1 {
    /// The unique identifier for the swap.
    pub swap_id: [u8; 32],
}

impl RefundV1 {
    pub fn new(swap_id: [u8; 32]) -> Self {
        Self { swap_id }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn amount_at_least_compares_value_with_matching_decimals() {
        let need = AmountV1::new("1000000000000000000".into(), 18);
        assert!(AmountV1::new("1000000000000000000".into(), 18).at_least(&need));
        assert!(AmountV1::new("2000000000000000000".into(), 18).at_least(&need));
        assert!(!AmountV1::new("1".into(), 18).at_least(&need));
    }

    #[test]
    fn amount_at_least_rejects_decimals_mismatch_and_unparseable() {
        let need = AmountV1::new("100".into(), 8);
        assert!(!AmountV1::new("100".into(), 18).at_least(&need));
        assert!(!AmountV1::new("abc".into(), 8).at_least(&need));
        assert!(!AmountV1::new("100".into(), 8).at_least(&AmountV1::new("xyz".into(), 8)));
    }

    fn sample_swap_id() -> [u8; 32] {
        let mut id = [0u8; 32];
        for (i, byte) in id.iter_mut().enumerate() {
            *byte = i as u8;
        }
        id
    }

    fn sample_secret_hash() -> [u8; 32] {
        let mut hash = [0u8; 32];
        for (i, byte) in hash.iter_mut().enumerate() {
            *byte = (255 - i) as u8;
        }
        hash
    }

    #[test]
    fn test_commitment_new() {
        let swap_id = sample_swap_id();
        let sender = "kaspa:sender_address".to_string();
        let sender_dest = "0xSenderDestAddr".to_string();
        let receiver = "kaspa:receiver_address".to_string();
        let amount = "50.12345678".to_string();
        let secret_hash = sample_secret_hash();
        let unlock_ts = 1700000000u64;
        let source = 1u8;
        let destination = 0u8;
        let decimals = 8u8;

        let commitment = CommitmentV1::new(
            swap_id,
            AddressesV1::new(sender.clone(), receiver.clone(), sender_dest.clone()),
            AmountV1::new(amount.clone(), decimals),
            secret_hash,
            unlock_ts,
            source,
            destination,
        );

        assert_eq!(commitment.swap_id, swap_id);
        assert_eq!(commitment.addresses.sender, sender);
        assert_eq!(commitment.addresses.sender_destination, sender_dest);
        assert_eq!(commitment.addresses.receiver, receiver);
        assert_eq!(commitment.amount.value, amount);
        assert_eq!(commitment.amount.decimals, decimals);
        assert_eq!(commitment.secret_hash, secret_hash);
        assert_eq!(commitment.unlock_ts, unlock_ts);
        assert_eq!(commitment.source, source);
        assert_eq!(commitment.destination, destination);
    }

    #[test]
    fn test_commitment_borsh_roundtrip() {
        let commitment = CommitmentV1::new(
            sample_swap_id(),
            AddressesV1::new(
                "sender".to_string(),
                "receiver".to_string(),
                "sender_dest".to_string(),
            ),
            AmountV1::new("100.0".to_string(), 18),
            sample_secret_hash(),
            1700000000,
            1,
            0,
        );
        let bytes = borsh::to_vec(&commitment).unwrap();
        let decoded = CommitmentV1::try_from_slice(&bytes).unwrap();
        assert_eq!(decoded, commitment);
    }

    #[test]
    fn test_reveal_new() {
        let swap_id = sample_swap_id();
        let secret = sample_secret_hash();

        let reveal = RevealV1::new(swap_id, secret);

        assert_eq!(reveal.swap_id, swap_id);
        assert_eq!(reveal.secret, secret);
    }

    #[test]
    fn test_reveal_borsh_roundtrip() {
        let reveal = RevealV1::new(sample_swap_id(), sample_secret_hash());
        let bytes = borsh::to_vec(&reveal).unwrap();
        let decoded = RevealV1::try_from_slice(&bytes).unwrap();
        assert_eq!(decoded, reveal);
    }

    #[test]
    fn test_refund_new() {
        let swap_id = sample_swap_id();

        let refund = RefundV1::new(swap_id);

        assert_eq!(refund.swap_id, swap_id);
    }

    #[test]
    fn test_refund_borsh_roundtrip() {
        let refund = RefundV1::new(sample_swap_id());
        let bytes = borsh::to_vec(&refund).unwrap();
        let decoded = RefundV1::try_from_slice(&bytes).unwrap();
        assert_eq!(decoded, refund);
    }
}
