use crate::error::HandlerError;
use crate::result::Result;
use crate::{Handler, required_init_lock_secs};
use alloy::primitives::U256;
use stroemnet_amounts::Amounts;
use stroemnet_protocol::ChannelId;

#[derive(Clone, Debug)]
/// A request to create a trade proposal, including the origin and destination channels and the input amount.
/// This is sent by users who dont necessarily run LP nodes.
pub struct SwapRequest {
    /// The channel id origin
    pub origin: u8,
    /// The destination channel id
    pub destination: u8,
    /// The amount to swap as a string, which will be parsed according to the origin channel's decimals
    pub amount: String,
}

#[derive(Clone, Debug)]
/// A trade proposal generated by an LP
/// in response to a swap request
pub struct TradeProposal {
    /// The origin of the swap from the persptive of the LP
    pub origin: ChannelId,
    /// The destination of the swap from the perspective of the LP
    pub destination: ChannelId,
    /// Amount in from the perspective of the LP
    pub amount_in: String,
    /// Amount out from the perspective of the LP,
    /// which is what the user will pay
    pub amount_out: String,
    /// The destination address of the sender, in this case the LP's address on the origin chain
    /// which is where the user should send funds to.
    pub sender_destination_address: String,
    /// The number of seconds that the user needs to put as additional offset from their current
    /// timestamp as unlock time for the commitment,
    pub commit_unlock_offset_secs: u64,
}

impl Handler {
    /// Create a trade proposal based on a swap request, which includes validating the request,
    pub async fn create_proposal(&self, request: &SwapRequest) -> Result<TradeProposal> {
        // Parse the requested origin and destination channels
        let origin = ChannelId::try_from(request.origin)?;
        let destination = ChannelId::try_from(request.destination)?;

        // Retrieve the usd price for the origin
        let source_usd_price = self
            .price_storage
            .get(&origin)
            .ok_or(HandlerError::MissingPriceData(origin))?;

        // Retrieve the destination usd price
        let destination_usd_price = self
            .price_storage
            .get(&destination)
            .ok_or(HandlerError::MissingPriceData(destination))?;

        // Conver the amount in to alloy u256
        let amount_in = U256::from_str_radix(&request.amount, 10)?;

        // Convert the amount to float
        let amount_in_f = amount_in.to_string().parse::<f64>()?;

        // Scale it from the origin decimal value to human readable "ether"
        let scale = 10u128.pow(origin.decimals() as u32) as f64;
        let amount_in_usd = (amount_in_f / scale) * source_usd_price;

        // If the amount in usd is smaller than the minimum allowed, return an error
        if amount_in_usd < self.config.min_trade_usd {
            return Err(HandlerError::TradeTooSmall {
                amount_in: request.amount.clone(),
                amount_in_usd,
                min_usd: self.config.min_trade_usd,
            });
        }

        // If the amount in usd is larger than the maximum allowed, return an error
        if amount_in_usd > self.config.max_trade_usd {
            return Err(HandlerError::TradeTooLarge {
                amount_in: request.amount.clone(),
                amount_in_usd,
                max_usd: self.config.max_trade_usd,
            });
        }

        // Use the amounts crate to compute proper output amoutn given
        // price, spread and decimals,
        let output = Amounts::amount_out(
            amount_in,
            source_usd_price,
            origin.decimals(),
            destination_usd_price,
            destination.decimals(),
            self.config.spread_percent,
        )?;

        tracing::info!(
            "Computed proposal output amount: {output} (amount_in: {amount_in}, source_price: {source_usd_price}, destination_price: {destination_usd_price}, spread_percent: {}, usd_value: {amount_in_usd})",
            self.config.spread_percent
        );

        // Retrieve our sender destination address,
        let sender_destination_address = self
            .address_lookup_table
            .get(&origin)
            .ok_or(HandlerError::UnknownChannel(origin))?
            .clone();

        // Compute the required offset for unlock from our requirements
        let commit_unlock_offset_secs =
            required_init_lock_secs(destination, self.config.commit_buffer_secs);

        Ok(TradeProposal {
            destination: origin,
            origin: destination,
            amount_out: request.amount.clone(),
            amount_in: output.to_string(),
            sender_destination_address,
            commit_unlock_offset_secs,
        })
    }
}

#[cfg(test)]
mod tests {
    use ahash::AHashMap;
    use alloy::primitives::U256;

    use crate::test_fixtures::{create_test_handler_with, default_test_config, lp_addresses};
    use crate::{Handler, HandlerError};
    use stroemnet_protocol::ChannelId;

    use super::SwapRequest;

    async fn setup_with_prices(kaspa_price: f64, eth_price: f64) -> Handler {
        let (handler, _) = create_test_handler_with(
            default_test_config(),
            &[
                (ChannelId::KaspaTn10, kaspa_price),
                (ChannelId::EthereumSepolia, eth_price),
            ],
            lp_addresses(),
        );
        handler
    }

    #[tokio::test]
    async fn create_proposal_valid_flow() {
        let handler = setup_with_prices(0.15, 3000.0).await;

        let request = SwapRequest {
            origin: ChannelId::EthereumSepolia as u8,
            destination: ChannelId::KaspaTn10 as u8,
            amount: "1000000000000000000".to_string(),
        };

        let proposal = handler.create_proposal(&request).await.unwrap();

        assert_eq!(proposal.origin, ChannelId::KaspaTn10);
        assert_eq!(proposal.destination, ChannelId::EthereumSepolia);
        let amount: U256 = U256::from_str_radix(&proposal.amount_out, 10).unwrap();
        assert!(amount > U256::ZERO, "Proposal amount should be positive");
    }

    #[tokio::test]
    async fn create_proposal_missing_source_price() {
        let (handler, _) = create_test_handler_with(
            default_test_config(),
            &[(ChannelId::KaspaTn10, 0.15)],
            AHashMap::new(),
        );

        let request = SwapRequest {
            origin: ChannelId::EthereumSepolia as u8,
            destination: ChannelId::KaspaTn10 as u8,
            amount: "1000".to_string(),
        };

        let err = handler.create_proposal(&request).await.unwrap_err();
        assert!(matches!(err, HandlerError::MissingPriceData(_)));
    }

    #[tokio::test]
    async fn create_proposal_invalid_amount() {
        let handler = setup_with_prices(0.15, 3000.0).await;

        let request = SwapRequest {
            origin: ChannelId::EthereumSepolia as u8,
            destination: ChannelId::KaspaTn10 as u8,
            amount: "not_a_number".to_string(),
        };

        let err = handler.create_proposal(&request).await;
        assert!(err.is_err());
    }
}
